const pulloverData = {
    lace00: {
        name: "Lace 00",
        babyPullover: 0,
        toddlerPullover: 0,
        childPullover: 0,
        adultSmallPullover: 0,
        adultLargePullover: 0,
        adultXxlPullover: 0,
    },
    fingering01: {
        name: "Fingering 01",
        babyPullover: 0,
        toddlerPullover: 0,
        childPullover: 0,
        adultSmallPullover: 0,
        adultLargePullover: 0,
        adultXxlPullover: 0,
    },
    sport02: {
        name: "Sport 02",
        babyPullover: 0,
        toddlerPullover: 0,
        childPullover: 0,
        adultSmallPullover: 0,
        adultLargePullover: 0,
        adultXxlPullover: 0,
    },
    dk03: {
        name: "DK 03",
        babyPullover: 0,
        toddlerPullover: 0,
        childPullover: 0,
        adultSmallPullover: 0,
        adultLargePullover: 0,
        adultXxlPullover: 0,
    },
    worsted04: {
        name: "Worsted 04",
        babyPullover: 550,
        toddlerPullover: 800,
        childPullover: 1200,
        adultSmallPullover: 1400,
        adultLargePullover: 1700,
        adultXxlPullover: 1850,
        },
    chunky05: {
        name: "Chunky 05",
        babyPullover: 0,
        toddlerPullover: 0,
        childPullover: 0,
        adultSmallPullover: 0,
        adultLargePullover: 0,
        adultXxlPullover: 0,
        },
}

